config/routes.rb
Rails.application.routes.draw do
  resources :cards #, only: [:index, :show]
  patch '/check_translation/:id', to: 'home#update', as: "/check_translation"
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :original, :translated, :review, presence: true
  validates :original, :translated, uniqueness: { case_sensitive: false }

  validate :on_review, on: :create

  before_validation  :no_equal
  scope :for_review, -> { where( 'review <= ?', Time.now ) }

  def comparison(txt)
    self.update_attributes(review: 3.days.from_now) if self.original == txt
  end

  protected

  def on_review
    self.review = -3.days.from_now
  end

  def no_equal
    if self.original.downcase == self.translated.downcase
      self.errors.add( :original, 'Оригинальный и переведённый тексты не должны быть равны друг другу')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :danger, :info, :warning
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, except: [:index, :new, :create]

  def index
    @cards = Card.all
  end

  def show
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new card_params
    if @card.save
      redirect_to @card
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @card.update card_params
      redirect_to @card
    else
      render :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to cards_path
  end

  private

  def set_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:original, :translated, :review)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @take_card = Card.for_review ? Card.for_review.take : Card.all.take
    # @take_card = Card.all.take
    # @take_card = Card.for_review.take
  end

  def update
    @card = Card.find(params[:id])
    if @card.comparison(params[:text])
      redirect_back(fallback_location: root_path,  success: 'угадал')
    else
      redirect_back(fallback_location: root_path, danger: 'извините, неправильно')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  # def take_card
  #   Card.where('review <= current_date').take
  # end
end

app/views/cards/_form.html.erb
<div class="jumbotron">
  
  <%= simple_form_for @card do |f| %>
    <%= f.input :original %>
    <%= f.input :translated %>
    <%= f.input :review %>
    <%= f.button :submit  %>
  <% end %>
</div>

app/views/cards/edit.html.erb
<h1>Изменить карточку</h1>

<%= render 'form' %>

app/views/cards/index.html.erb
<h1>Все карточки: <%= @cards.all.count %> шт.</h1>
<% @cards.each do |card| %>
<p>
  <%= link_to card.original, card %> |
  <%= card.review.to_date.strftime("%d %B, %Y") if card.review %> |
  <%= link_to 'Изменить', edit_card_path(card) %> |
   <%= link_to 'Удалить', card, method: :delete, data: { confirm: 'Удалить насовсем?' } %>

</p>
<% end %>

app/views/cards/new.html.erb
<h1>Новая карточка</h1>

<%= render 'form' %>

app/views/cards/show.html.erb
<h1> <%= @card.translated %> </h1>

app/views/home/_take_form.html.erb
<%= form_for(@take_card, url: check_translation_path(@take_card),  method: "patch") do |f| %>
  <%= text_field_tag(:text) %>
  <%= f.submit %>
<% end %>

app/views/home/index.html.erb
 <div class="jumbotron font-center">

      <p style="font-size: 22px;">
        Первый в мире удобный менеджер флеш-карточек. Именно так.
      </p>

 </div>

<div class="panel panel-default">
  <% if @take_card %>

    <div class="panel-heading"><%= @take_card.translated %></div>

    <div class="panel-body">
      <p>
        <%= render 'home/take_form' %>
      </p>
    </div>

  <% else %>
    <div class="panel-body">
      <h1>Карточек нет</h1>
    </div>

  <% end %>

</div>

app/views/layouts/_navbar.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="/">Бренд</a></li>
  <li role="presentation"> <%= link_to 'Все карточки', cards_path %> </li>
  <li role="presentation"><%= link_to 'Добавить карточку', new_card_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Флэшкарточкер</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <div class="container">
    <%= render 'layouts/navbar' %>
    </div>

   <section id="container">

    <header class="clearfix">
      <h1>Флэшкарточкер</h1>

    </header>

    <section>
<% flash.each do |name, message| %>
            <div class="alert alert-<%= name %>">
              <%= message %>
            </div>
          <% end %>

    <%= yield %>


      </section>

  </section>
  </body>
</html>